version: '3.1'
services:
  web:
    image: 'spring-boot-docker-latest'
    container_name: 'template-spring-boot-java-master_web_1'
    build:
      context: docker/
      dockerfile: Dockerfile
    ports: 
    - '8080:8080'
    depends_on:
    - assessment-mysql-db
  assessment-mysql-db:
    image: 'mysql:8.0'
    container_name: 'mysql'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: 'always'
    environment:
      MYSQL_DATABASE: 'assessment'
      MYSQL_USER: 'db_user'
      MYSQL_PASSWORD: '8b3b91c7'
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    ports:
    - '3306:3306'